// Auth User - Success
# @name login
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###

@authToken = {{login.response.body.token}}
POST {{URL}}/api/orders
Content-Type: 'application/json'
Authorization: Bearer {{authToken}}

{
  "orderItems": [
    {
      "_id": "60229723375d650950a523e7",
      "product": "602295e8a1078c1b68defe47",
      "name": "Logitech G-Series Gaming Mouse",
      "image": "/images/mouse.jpg",
      "price": 49.99,
      "qty": 1
    },]
    "shippingAddress": {
    "address": "39 Heron Close",
    "city": "Blyth",
    "postCode": "NE24 3QQ",
    "country": "United Kingdom"
  },
  "taxPrice": 7.5,
  "shippingPrice": 100,
  "totalPrice": 157.49,
}
###

@authToken = {{login.response.body.token}}
GET {{URL}}/api/orders/60229723375d650950a523e6
Content-Type: 'application/json'
Authorization: Bearer {{authToken}}

###