// All Products
GET {{URL}}/api/products

###
// Get existing product
GET {{URL}}/api/products/602be619b143f91838658bac

###
// Get missing product
GET {{URL}}/api/products/60102dd894ab0d3118f5a1b0

###
// Get invalid product
GET {{URL}}/api/products/1

###
// Get stock levels
@authToken = {{login.response.body.token}}
GET {{URL}}/api/products/stock
Authorization: Bearer {{authToken}}

###

// User Login
# @name login
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "sParhawk72"
}

###

// Create review - protected route
@authToken = {{login.response.body.token}}
POST {{URL}}/api/products/602be619b143f91838658bae/reviews
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "rating": 4.5,
  "comment": "Pretty nice!"
}

###
