// Auth User - Success
# @name login
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "1234567"
}

###

// Auth User - Success
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}

###

// Auth User - Unknown user
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "doesnotexist@example.com",
  "password": "12345"
}

###

// Auth User - Bad password
POST {{URL}}/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "12345"
}

###

// Auth User - protected route
@authToken = {{login.response.body.token}}
GET {{URL}}/api/users/profile
Authorization: Bearer {{authToken}}

###

// Register user - new
POST {{URL}}/api/users
Content-Type: application/json

{
  "name" : "Dummy",
  "password": "654321",
  "email": "dummy@example.com"
}

###

// Register user - existing
POST {{URL}}/api/users
Content-Type: application/json

{
  "name" : "admin",
  "password": "654321",
  "email": "admin@example.com"
}

###

// Update profile
PATCH {{URL}}/api/users/profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name" : "Admin",
  "email": "john.doe@example.com",
  "password": "1234567"
}
